In [3]:
import pandas as pd
import numpy as np

print("Libraries imported")

Libraries imported

In [4]:
file1 = "/content/sample_data/metadata1.csv"
file2 = "/content/sample_data/metadata2.csv"
file3 = "/content/sample_data/metadata3.csv"



print("files are uploaded")

files are uploaded

In [5]:
df_1 = pd.read_csv(file1)
df_2 = pd.read_csv(file2)
df_3 = pd.read_csv(file3)


print(df_1.shape)
print(df_2.shape)
print(df_3.shape)

(744, 4)
(1000, 4)
(58, 4)

In [7]:
df = [df_1,df_2,df_3]


for df in df:
  print(df.columns)

Index(['song_id', 'Artist', 'Song title', 'Genre'], dtype='object')
Index(['Id', 'Artist', 'Track', 'Genre'], dtype='object')
Index(['id', 'title', 'artist', 'genre'], dtype='object')

In [8]:
shared_column = ["id", "artist", "title", "genre"]

In [23]:
df_1 = df_1.rename(columns=
 {
    "song_id":shared_column[0],
    "Artist": shared_column[1],
    "Song title": shared_column[2],
    "Genre": shared_column[3]
  }
)

df_1 = df_1[shared_column]


unwanted_symbols = "\t"
df_1 = df_1.replace(r'\t', '', regex=True)
df_1

,id,artist,title,genre
0,2,The New Mystikal Troubadours,Tonight A Lonely Century,Blues
1,3,Kevin MacLeod,DD Groove,Blues
2,4,Kevin MacLeod,Slow Burn,Blues
3,5,My Bubba & Mi,Nothing Much,Blues
4,7,Kevin MacLeod,Hustle,Blues
...,...,...,...,...
739,995,Benjamin Bret,Honte De Toi,Rock
740,996,Jahzzar,Fireworks,Rock
741,997,Halloween,Monster On Campus,Rock
742,999,Jahzzar,So Easy,Rock
743,1000,Republic Of Lights-Got You Surrounded,Single,Rock

In [14]:
df_2 = df_2.rename(columns=
 {
    "Id":shared_column[0],
    "Artist": shared_column[1],
    "Track": shared_column[2],
    "Genre": shared_column[3]
  }
)

df_2 = df_2[shared_column]
df_2

,id,artist,title,genre
0,1001,The Rope River Blues Band,Weatherman,SoulRB-Country-Folk-Pop-Experimental-Rock-Blues
1,1002,Kidney Brothers (The Numbers Band),Wolf,Blues-SoulRB-Rock
2,1003,Samm Bennett,My My My,Blues-SoulRB-Folk-Experimental
3,1004,The Rope River Blues Band,Visitor,SoulRB-Country-Folk-Pop-Rock-Blues
4,1005,Brother JT,Summer,Blues-SoulRB-Rock
...,...,...,...,...
995,1996,The Matt Kurz One,BEAT 'EM,Rock
996,1997,Ariel Pink's Haunted Graffiti,For Kate I Wait,Rock
997,1998,Fresh Body Shop,My Artificial Sun,Rock
998,1999,The Gotobeds,New Dress,Rock
999,2000,Fresh Body Shop,Never End Up Like This,Rock

In [19]:
df_3 = df_3.rename(columns=
 {
    "id":shared_column[0],
    "artist": shared_column[2],
    "title": shared_column[1],
    "genre": shared_column[3]
  }
)

df_3 = df_3[shared_column]
df_3

,id,artist,title,genre
0,2001,Creepoid,Old Tree,Rock
1,2002,Amar Lal,Spring Day 1,classical
2,2003,Joel Helander,Excessive Resistance to Change,Classical
3,2004,Aimee Norwich,Flying,Folk
4,2005,Ava Luna,Waterduct,Rock
5,2006,Clara Berry and Wooldog,Air Traffic,Jazz
6,2007,Dreamers of the Ghetto,Heavy Love,Pop
7,2008,Invisible Familiars,Disturbing Wildlife,Indie Pop
8,2009,Joel Helander,Definition,Classical
9,2010,Karim Douaidy,Yatora,World/Folk
10,2011,Lushlife,Toynbee Suite,Rap
11,2012,Matthew Entwistle,Impressions of Saturn,Classical
12,2013,Matthew Entwistle,The Arch,Classical
13,2014,Meaxic,You Listen,Rock
14,2015,NYU,Bester Jungling,Classical
15,2016,Music Delta,Chinese Jiang Nan,World/Folk
16,2017,Music Delta,Funk Jazz,Jazz
17,2018,Music Delta,Modal Jazz,Jazz
18,2019,Phoenix,The Broken Pledge - Chicago Reel,World/Folk
19,2020,Phoenix,The Collier's Daughter,World/Folk
20,2021,Port St Willow,Stay Even,Alternative/Indie
21,2022,NYU,Mignon (Kennst du das Land) Op.92a Mvt.1,Classical
22,2023,Strand of Oaks,Spacestation,Pop
23,2024,Tabla Breakbeat Science,Captain Sky,Electronic/Fusion
24,2025,Tabla Breakbeat Science,Rock Steady,Electronic/Fusion
25,2026,Tabla Breakbeat Science,Scorpio,Electronic/Fusion
26,2027,The Districts,Vermont,Rock
27,2028,The Scarlet Brand,Les Fleurs Du Mal,Rock
28,2029,A Classic Education,Night Owl,Indie rock / Alternative pop
29,2030,In Faded Glory,990,rock
30,2031,No,Go,folk
31,2032,Kryptic Mood,Song For Jade,pop
32,2033,Hunt Club,Uranium,rock
33,2034,Jacques COUTURIER,Hey! beauty,pop
34,2035,Die Partysahnen,Mit dem Unibalett im Ulmer Monster tanzen,rock
35,2036,Feel-ipson,Feel-ipson,pop
36,2037,engeo,Dreamworld,pop
37,2038,Fabrice Collette,rouge et blues,blues
38,2039,FOOL DADAZ FIRE,Le Blues du Fantome,pop
39,2040,Ralph Buckley,FUCK THE WAR,acoustic
40,2041,Steven Dunston,Little White Church,pop
41,2042,Ogg Vorbis,Classical Delay,groove
42,2043,Matti Paalanen,Summer,jazz
43,2044,Manuzik,Habanera,world
44,2045,Behrang Shegarfkar,Jazzy Mode,jazz
45,2046,PELdeNOZ,O Pindo,jazz
46,2047,AdHoc,La note en cage,jazz
47,2048,Maneros productions,Travelling in balochistan - late night highway,rock
48,2049,Steve.e!,Lonely Fool,electronic
49,2050,BeatRaider,Homecoming,hiphop
50,2051,elbrujo,a fleur de peau,rap
51,2052,Juice lee,Les 3 singes,rap
52,2053,ADC LEVEL,Neon,electronic
53,2054,Tom La Meche,Interlude,jazz
54,2055,Goo Goo Cluster,Vide grenier,blues
55,2056,Ruediger Kramer,happy child singing,jazz
56,2057,La Verue,Au Feu,rock
57,2058,La Verue,Inside Views,rock

In [31]:
df = pd.concat([df_1, df_2,df_3], ignore_index=True)
df.tail(500)


df.to_json("combinedmetadata.csv")

In [32]:
dfCom = pd.read_json("/content/combinedmetadata.csv")

In [35]:
dfCom.notna().count()

id        1802
artist    1802
title     1802
genre     1802
dtype: int64

In [36]:
embed_df = pd.read_json("/content/sample_data/music2vec_embeddings_13.json")

In [37]:
embed_df.shape

(1795, 2)

In [38]:
embed_df.head()

   0                                                  1
0  2  [0.414761424064636, -0.14344373345375, 0.32250...
1  3  [0.11872563511133101, -0.10112874209880801, 0....
2  4  [0.470960527658462, 0.22900389134883803, 0.229...
3  5  [0.7635553479194641, -0.10898533463478001, 0.2...
4  7  [-0.241142109036445, 0.368344366550445, -0.295...

In [39]:
embed_df.columns

RangeIndex(start=0, stop=2, step=1)

In [41]:
embed_df[0]

0          2
1          3
2          4
3          5
4          7
        ...
1790    2054
1791    2055
1792    2056
1793    2057
1794    2058
Name: 0, Length: 1795, dtype: int64

In [43]:
embed_df[1]

0       [0.414761424064636, -0.14344373345375, 0.32250...
1       [0.11872563511133101, -0.10112874209880801, 0....
2       [0.470960527658462, 0.22900389134883803, 0.229...
3       [0.7635553479194641, -0.10898533463478001, 0.2...
4       [-0.241142109036445, 0.368344366550445, -0.295...
                              ...
1790    [-0.308220475912094, -0.402178585529327, -0.08...
1791    [0.6584870219230651, -0.188769653439521, -0.02...
1792    [0.16927760839462203, -0.037881512194871, -0.3...
1793    [0.836810410022735, 0.292294293642044, 0.18960...
1794    [0.7328771948814391, -0.18728640675544703, 0.4...
Name: 1, Length: 1795, dtype: object

In [45]:
missing_rows = dfCom[~dfCom['id'].isin(embed_df[0])]
missing_rows

        id                   artist                  title              genre
1754  2011                 Lushlife          Toynbee Suite                Rap
1755  2012        Matthew Entwistle  Impressions of Saturn          Classical
1757  2014                   Meaxic             You Listen               Rock
1764  2021           Port St Willow              Stay Even  Alternative/Indie
1767  2024  Tabla Breakbeat Science            Captain Sky  Electronic/Fusion
1768  2025  Tabla Breakbeat Science            Rock Steady  Electronic/Fusion
1769  2026  Tabla Breakbeat Science                Scorpio  Electronic/Fusion

In [47]:
print(dfCom['id'].count() -  embed_df[0].count())
print(missing_rows['id'].count())

7
7

In [48]:
dfComFil = dfCom.drop(missing_rows.index)

In [54]:
print(dfComFil.count())
print(embed_df.count())

id        1795
artist    1795
title     1795
genre     1795
dtype: int64
0    1795
1    1795
dtype: int64

In [60]:
merged_df = pd.merge(dfComFil, embed_df, left_on='id', right_on=0, how='left')
merged_df = merged_df.drop(columns=[0])
merged_df = merged_df.rename(columns={1: 'embedding'})

display(merged_df.head())

,id,artist,title,genre,embedding
0,2,The New Mystikal Troubadours,Tonight A Lonely Century,Blues,"[0.414761424064636, -0.14344373345375, 0.32250..."
1,3,Kevin MacLeod,DD Groove,Blues,"[0.11872563511133101, -0.10112874209880801, 0...."
2,4,Kevin MacLeod,Slow Burn,Blues,"[0.470960527658462, 0.22900389134883803, 0.229..."
3,5,My Bubba & Mi,Nothing Much,Blues,"[0.7635553479194641, -0.10898533463478001, 0.2..."
4,7,Kevin MacLeod,Hustle,Blues,"[-0.241142109036445, 0.368344366550445, -0.295..."

In [64]:
merged_df.to_json("metadata.json", orient='records', indent=4)

In [65]:
merged_df.count()

id           1795
artist       1795
title        1795
genre        1795
embedding    1795
dtype: int64

In [66]:
arousal = pd.read_csv("/content/sample_data/arousal.csv")
valence = pd.read_csv("/content/sample_data/valence.csv")

In [69]:
print(arousal.columns)
print(valence.columns)

Index(['song_id', 'sample_15000ms', 'sample_15500ms', 'sample_16000ms',
       'sample_16500ms', 'sample_17000ms', 'sample_17500ms', 'sample_18000ms',
       'sample_18500ms', 'sample_19000ms',
       ...
       'sample_622000ms', 'sample_622500ms', 'sample_623000ms',
       'sample_623500ms', 'sample_624000ms', 'sample_624500ms',
       'sample_625000ms', 'sample_625500ms', 'sample_626000ms',
       'sample_626500ms'],
      dtype='object', length=1225)
Index(['song_id', 'sample_15000ms', 'sample_15500ms', 'sample_16000ms',
       'sample_16500ms', 'sample_17000ms', 'sample_17500ms', 'sample_18000ms',
       'sample_18500ms', 'sample_19000ms',
       ...
       'sample_621500ms', 'sample_622000ms', 'sample_622500ms',
       'sample_623000ms', 'sample_623500ms', 'sample_624000ms',
       'sample_624500ms', 'sample_625000ms', 'sample_625500ms',
       'sample_626000ms'],
      dtype='object', length=1224)

In [72]:
print(arousal.shape)
print(valence.shape)

(1802, 1225)
(1802, 1224)

In [74]:
print(arousal.notnull().count())
print(valence.notnull().count())

song_id            1802
sample_15000ms     1802
sample_15500ms     1802
sample_16000ms     1802
sample_16500ms     1802
                   ...
sample_624500ms    1802
sample_625000ms    1802
sample_625500ms    1802
sample_626000ms    1802
sample_626500ms    1802
Length: 1225, dtype: int64
song_id            1802
sample_15000ms     1802
sample_15500ms     1802
sample_16000ms     1802
sample_16500ms     1802
                   ...
sample_624000ms    1802
sample_624500ms    1802
sample_625000ms    1802
sample_625500ms    1802
sample_626000ms    1802
Length: 1224, dtype: int64

In [75]:
missing_song_ids = missing_rows['id']

arousal_fil = arousal[~arousal['song_id'].isin(missing_song_ids)]
valence_fil = valence[~valence['song_id'].isin(missing_song_ids)]

In [78]:
arousal_fil.head()

,song_id,sample_15000ms,sample_15500ms,sample_16000ms,sample_16500ms,sample_17000ms,sample_17500ms,sample_18000ms,sample_18500ms,sample_19000ms,...,sample_622000ms,sample_622500ms,sample_623000ms,sample_623500ms,sample_624000ms,sample_624500ms,sample_625000ms,sample_625500ms,sample_626000ms,sample_626500ms
0,2,-0.109386,-0.114942,-0.116413,-0.118613,-0.126457,-0.133199,-0.136855,-0.144713,-0.138985,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,-0.110846,-0.123973,-0.131103,-0.135956,-0.140775,-0.144664,-0.163118,-0.165218,-0.158858,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4,0.222327,0.179446,0.178388,0.184056,0.176042,0.178720,0.176345,0.175793,0.176154,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5,-0.255613,-0.251579,-0.251958,-0.251124,-0.250763,-0.251957,-0.251957,-0.251957,-0.251957,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7,0.464234,0.460789,0.460991,0.461046,0.457240,0.465702,0.471809,0.469918,0.473377,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [76]:
print('Shape of arousal_fil:', arousal_fil.shape)
print('Shape of valence_fil:', valence_fil.shape)

Shape of arousal_fil: (1795, 1225)
Shape of valence_fil: (1795, 1224)

In [94]:
arousal_mean = arousal_fil.groupby('song_id').mean().mean(axis=1).rename('arousal_mean')
valence_mean = valence_fil.groupby('song_id').mean().mean(axis=1).rename('valence_mean')

In [95]:
# Drop any existing redundant mean columns before merging to ensure a clean state
columns_to_drop = [col for col in merged_df.columns if 'valence_mean' in col or 'arousal_mean' in col]
merged_df = merged_df.drop(columns=columns_to_drop)

# Merge the correctly named valence_mean Series
merged_df = merged_df.merge(
    valence_mean,
    left_on='id',
    right_index=True,
    how='left'
)

# Merge the correctly named arousal_mean Series
merged_df = merged_df.merge(
    arousal_mean,
    left_on='id',
    right_index=True,
    how='left'
)

display(merged_df.head())

,id,artist,title,genre,embedding,valence_mean,arousal_mean
0,2,The New Mystikal Troubadours,Tonight A Lonely Century,Blues,"[0.414761424064636, -0.14344373345375, 0.32250...",-0.215511,-0.197517
1,3,Kevin MacLeod,DD Groove,Blues,"[0.11872563511133101, -0.10112874209880801, 0....",-0.265855,-0.193187
2,4,Kevin MacLeod,Slow Burn,Blues,"[0.470960527658462, 0.22900389134883803, 0.229...",0.155210,0.243072
3,5,My Bubba & Mi,Nothing Much,Blues,"[0.7635553479194641, -0.10898533463478001, 0.2...",0.140160,-0.236207
4,7,Kevin MacLeod,Hustle,Blues,"[-0.241142109036445, 0.368344366550445, -0.295...",0.332455,0.376292

In [96]:
merged_df.to_json("metadata.json", orient='records', indent=4)

In [99]:
# Filtering for rows where -1 > Arousal > 1 and -1 > Valence > 1 (mathematically impossible)
extremely_out_of_range_data = merged_df[
    ((-1 > merged_df['arousal_mean']) & (merged_df['arousal_mean'] > 1)) |
    ((-1 > merged_df['valence_mean']) & (merged_df['valence_mean'] > 1))
]
display(extremely_out_of_range_data)

Empty DataFrame
Columns: [id, artist, title, genre, embedding, valence_mean, arousal_mean]
Index: []

As you can see, the above DataFrame is empty. This is because a number cannot be simultaneously less than -1 and greater than 1.

If you intended to find rows where Arousal or Valence are *outside* the range of -1 to 1 (i.e., less than -1 OR greater than 1), here is the corrected code:

In [98]:
# Filtering for rows where Arousal < -1 or Arousal > 1
# AND Valence < -1 or Valence > 1

out_of_range_data = merged_df[
    ((merged_df['arousal_mean'] < -1) | (merged_df['arousal_mean'] > 1)) |
    ((merged_df['valence_mean'] < -1) | (merged_df['valence_mean'] > 1))
]

display(out_of_range_data)

Empty DataFrame
Columns: [id, artist, title, genre, embedding, valence_mean, arousal_mean]
Index: []